name: Sync Bucket
on: push

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - uses: goodsmileduck/yandex-serverless-action@master
      env:
        SOURCE_DIR: '.'
        ZONE: 'ru-central1-a'
        FUNCTION_NAME: 'cuckoocert'
        RUNTIME: 'nodejs12'
        ENTRYPOINT: 'main.lambdaEntryPoint'
        ENVIRONMENT: "SOCKS_HOST=${{ secrets.SOCKS_HOST }},SOCKS_PORT=${{ secrets.SOCKS_PORT }},SOCKS_USERNAME=${{ secrets.SOCKS_USERNAME }},SOCKS_PASSWORD=${{ secrets.SOCKS_PASSWORD }},EXPIRY_THRESHOLD=${{ secrets.EXPIRY_THRESHOLD }},CHAT_ID=${{ secrets.CHAT_ID }},BOT_TOKEN=${{ secrets.BOT_TOKEN }}"
        CLOUD_ID: ${{ secrets.CLOUD_ID }}
        FOLDER_ID: ${{ secrets.FOLDER_ID }}
        TOKEN: ${{ secrets.TOKEN }}
        BUCKET: ${{ secrets.BUCKET }}
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        TIMEOUT: 30s
