name: Sync Bucket
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: goodsmileduck/yandex-serverless-action@master
      env:
        SOURCE_DIR: '.'
        ZONE: 'ru-central1-a'
        FUNCTION_NAME: 'handler'
        RUNTIME: 'python37'
        ENTRYPOINT: 'main.handler'
        ENVIRONMENT: DEBUG=True,COUNT=1
        CLOUD_ID: ${{ secrets.CLOUD_ID }}
        FOLDER_ID: ${{ secrets.FOLDER_ID }}
        TOKEN: ${{ secrets.TOKEN }}
        BUCKET: ${{ secrets.BUCKET }}
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
